"""Trading 212 activity statement parser.

The activity statement contains executed trades and an open positions summary.
We use the open positions as the best source for identifiers and quantities,
then merge them into the current holdings snapshot values shown in Trading 212.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path

from sqlalchemy import select

from app.db.database import session_scope
from app.db.models import Account, BalanceSnapshot, DataSource, Domain, SourceStatus
from app.services import get_default_user_id


_GENERATED_RE = re.compile(r"Generated by Trading 212 UK Ltd\. on (\d{1,2} \w+ \d{4})")
_POSITION_RE = re.compile(
    r"^(?P<ticker>[A-Z0-9]+)\s+"
    r"(?P<isin>[A-Z0-9]{12})\s+"
    r"(?P<currency>USD|GBX|GBP|EUR)\s+"
    r"(?P<quantity>-?\d+(?:\.\d+)?)\s+"
    r"(?P<average_price>-?\d+(?:\.\d+)?)\s+"
    r"(?P<price>-?\d+(?:\.\d+)?)\s+"
    r"(?P<return_native>-?\d+(?:\.\d+)?)\s+"
    r"(?P<value_native>-?\d+(?:\.\d+)?)\s+"
    r"(?P<fx_rate>-?\d+(?:\.\d+)?)\s+"
    r"(?P<return_gbp>-?\d+(?:\.\d+)?)\s+"
    r"(?P<value_gbp>-?\d+(?:\.\d+)?)$"
)

_TICKER_NAMES = {
    "ARKK": "ARK Innovation (Acc)",
    "BOTZ": "Global X Robotics & Artificial Intelligence (Acc)",
    "DEVSF": "DevvStream",
    "IITU": "iShares S&P 500 Information Technology Sector (Acc)",
    "NATP": "Future of Defence UCITS ETF (Acc)",
    "QBTS": "D-Wave Quantum",
    "QUBT": "Quantum Computing",
    "RGTI": "Rigetti Computing",
    "RKLB": "Rocket Lab Corporation",
    "SAEM": "iShares MSCI EM IMI Screened (Acc)",
    "SSIT": "Seraphim Space Investment Trust",
    "SXR8": "iShares Core S&P 500 (Acc)",
    "VHYL": "Vanguard FTSE All-World High Dividend Yield (Dist)",
    "VWRP": "Vanguard FTSE All-World (Acc)",
}


@dataclass(frozen=True)
class ActivityPosition:
    ticker: str
    name: str
    isin: str
    instrument_currency: str
    quantity: float
    average_price: float
    price: float
    return_gbp: float
    value_gbp: float
    fx_rate: float


@dataclass(frozen=True)
class Trading212ActivityStatement:
    path: Path
    generated_on: date
    positions: list[ActivityPosition]


def parse_activity_statement_pdf(path: str | Path) -> Trading212ActivityStatement:
    import pdfplumber

    pdf_path = Path(path).expanduser()
    chunks: list[str] = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            chunks.append(page.extract_text(x_tolerance=1, y_tolerance=3) or "")
    return parse_activity_statement_text("\n".join(chunks), pdf_path)


def parse_activity_statement_text(text: str, path: str | Path = "") -> Trading212ActivityStatement:
    generated_on = _parse_generated_on(text) or date.today()
    positions: list[ActivityPosition] = []
    in_positions = False
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if line == "Open positions":
            in_positions = True
            continue
        if in_positions and line.startswith("Stocks ISA account - cash breakdown"):
            break
        if not in_positions:
            continue
        match = _POSITION_RE.match(line)
        if not match:
            continue
        ticker = match.group("ticker")
        positions.append(
            ActivityPosition(
                ticker=ticker,
                name=_TICKER_NAMES.get(ticker, ticker),
                isin=match.group("isin"),
                instrument_currency=match.group("currency"),
                quantity=float(match.group("quantity")),
                average_price=float(match.group("average_price")),
                price=float(match.group("price")),
                return_gbp=float(match.group("return_gbp")),
                value_gbp=float(match.group("value_gbp")),
                fx_rate=float(match.group("fx_rate")),
            )
        )
    return Trading212ActivityStatement(Path(path), generated_on, positions)


def import_activity_statement(
    path: str | Path,
    *,
    user_id: int | None = None,
    account_value: float | None = None,
    cash_value: float | None = None,
) -> dict:
    statement = parse_activity_statement_pdf(path)
    uid = user_id if user_id is not None else get_default_user_id()
    if uid is None:
        raise RuntimeError("No ORION user exists yet. Launch ORION once first.")

    with session_scope() as session:
        source = session.scalars(
            select(DataSource).where(DataSource.user_id == uid, DataSource.key == "trading212")
        ).first()
        if source is None:
            source = DataSource(
                user_id=uid,
                key="trading212",
                name="Trading 212",
                domain=Domain.finance,
                status=SourceStatus.connected,
            )
            session.add(source)
            session.flush()
        source.status = SourceStatus.connected
        source.last_synced_at = datetime.now()

        account = _isa_account(session, uid, source.id)
        if account is None:
            account = Account(
                user_id=uid,
                source_id=source.id,
                name="Trading 212 Stocks & Shares ISA",
                kind="investment",
                currency="GBP",
                extra={},
            )
            session.add(account)
            session.flush()

        extra = dict(account.extra or {})
        current_holdings = extra.get("holdings") if isinstance(extra.get("holdings"), list) else []
        enriched = _merge_positions(current_holdings, statement.positions)
        extra.update(
            {
                "holdings": enriched,
                "holdings_status": "activity_statement_enriched_live_screen",
                "activity_statement_path": str(Path(path).expanduser()),
                "activity_statement_generated_on": statement.generated_on.isoformat(),
                "cash_value_minor": _money_minor(cash_value) if cash_value is not None else 0,
            }
        )
        if account_value is not None:
            extra["investments_value_minor"] = _money_minor(account_value)
        elif cash_value is not None:
            total = sum(float(row.get("value") or 0.0) for row in enriched) + float(cash_value)
            extra["investments_value_minor"] = _money_minor(total - float(cash_value))
        account.extra = extra

        if account_value is not None:
            _upsert_balance(session, account.id, statement.generated_on, _money_minor(account_value))

    return {
        "positions": len(statement.positions),
        "generated_on": statement.generated_on.isoformat(),
        "account_value": account_value,
        "cash_value": cash_value,
    }


def _merge_positions(current_holdings: list[dict], positions: list[ActivityPosition]) -> list[dict]:
    by_name = {str(row.get("name")): dict(row) for row in current_holdings}
    for pos in positions:
        row = by_name.get(pos.name, {"name": pos.name, "value": pos.value_gbp, "sources": ["Activity Statement"]})
        row.update(
            {
                "ticker": pos.ticker,
                "isin": pos.isin,
                "instrument_currency": pos.instrument_currency,
                "quantity": pos.quantity,
                "average_price": pos.average_price,
                "statement_price": pos.price,
                "activity_statement_value": pos.value_gbp,
                "activity_statement_return": pos.return_gbp,
                "fx_rate": pos.fx_rate,
            }
        )
        if not row.get("sources"):
            row["sources"] = ["Activity Statement"]
        by_name[pos.name] = row
    total_value = sum(float(row.get("value") or 0.0) for row in by_name.values()) or 1.0
    out = []
    for row in by_name.values():
        row["portfolio_weight_pct"] = round(float(row.get("value") or 0.0) / total_value * 100.0, 2)
        out.append(row)
    return sorted(out, key=lambda item: float(item.get("value") or 0.0), reverse=True)


def _isa_account(session, user_id: int, source_id: int) -> Account | None:
    accounts = session.scalars(
        select(Account).where(Account.user_id == user_id, Account.source_id == source_id)
    ).all()
    return next(
        (
            row
            for row in accounts
            if (row.extra or {}).get("statement_label") == "ISA Account"
            or "stocks & shares isa" in row.name.lower()
        ),
        None,
    )


def _upsert_balance(session, account_id: int, snapshot_date: date, balance_minor: int) -> None:
    existing = session.scalars(
        select(BalanceSnapshot).where(
            BalanceSnapshot.account_id == account_id,
            BalanceSnapshot.snapshot_date == snapshot_date,
        )
    ).first()
    if existing is None:
        session.add(
            BalanceSnapshot(
                account_id=account_id,
                snapshot_date=snapshot_date,
                balance_minor=balance_minor,
                currency="GBP",
            )
        )
    else:
        existing.balance_minor = balance_minor
        existing.currency = "GBP"


def _parse_generated_on(text: str) -> date | None:
    match = _GENERATED_RE.search(text)
    if not match:
        return None
    try:
        return datetime.strptime(match.group(1), "%d %B %Y").date()
    except ValueError:
        return None


def _money_minor(value) -> int:
    return int(round(float(value) * 100))
