"""Trading 212 PDF statement ingestion.

Trading 212's transaction statement is not a positions report: it includes
account values and cash movements, but no instrument holdings or quantities.
This importer therefore records the statement-backed ISA value and cash flows
without inventing a portfolio composition.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path

from sqlalchemy import select

from app.db.database import session_scope
from app.db.models import Account, BalanceSnapshot, DataSource, Domain, SourceStatus, Transaction
from app.services import get_default_user_id


_ACCOUNT_RE = re.compile(r"^(ISA Account|Cash ISA Account|Invest Account)$")
_VALUE_RE = re.compile(r"^Account value:\s*£([0-9,]+(?:\.[0-9]{2})?)$")
_ID_RE = re.compile(r"^Account ID:\s*(\d+)$")
_ROW_RE = re.compile(
    r"^(?P<amount>-?\d+(?:\.\d+)?)\s+GBP\s+"
    r"(?P<when>\d{2}/\d{2}/\d{4}\s+\d{2}:\d{2}:\d{2})\s+"
    r"(?P<note>.+)$"
)
_PERIOD_RE = re.compile(r"Document period\s+(\d{2}\.\d{2}\.\d{4})\s+-\s+(\d{2}\.\d{2}\.\d{4})")
_GENERATED_RE = re.compile(r"Generated by Trading 212 UK Ltd\. on (\d{1,2} \w+ \d{4})")
_TRANSACTION_ID_RE = re.compile(r"Transaction ID:\s*([0-9a-f-]{20,})", re.IGNORECASE)


@dataclass(frozen=True)
class Trading212Movement:
    amount_minor: int
    currency: str
    booked_at: date
    category: str
    description: str
    external_id: str


@dataclass
class Trading212StatementAccount:
    label: str
    account_id: str = ""
    value_minor: int = 0
    currency: str = "GBP"
    movements: list[Trading212Movement] = field(default_factory=list)


@dataclass
class Trading212Statement:
    path: Path
    generated_on: date
    period_start: date | None
    period_end: date | None
    accounts: list[Trading212StatementAccount]


def parse_statement_pdf(path: str | Path) -> Trading212Statement:
    """Parse a Trading 212 transactions statement PDF."""
    import pdfplumber

    pdf_path = Path(path)
    chunks: list[str] = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            chunks.append(page.extract_text(x_tolerance=1, y_tolerance=3) or "")
    return parse_statement_text("\n".join(chunks), pdf_path)


def parse_statement_text(text: str, path: str | Path = "") -> Trading212Statement:
    generated_on = _parse_generated_on(text) or date.today()
    period_start, period_end = _parse_period(text)
    accounts: list[Trading212StatementAccount] = []
    current: Trading212StatementAccount | None = None

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if _ACCOUNT_RE.match(line):
            current = Trading212StatementAccount(label=line)
            accounts.append(current)
            continue
        if current is None:
            continue
        if match := _VALUE_RE.match(line):
            current.value_minor = _money_minor(match.group(1))
            continue
        if match := _ID_RE.match(line):
            current.account_id = match.group(1)
            continue
        if line.startswith(("AMOUNT CURRENCY", "Trading 212 is", "Financial Conduct")):
            continue
        if line == "No data available":
            continue
        if match := _ROW_RE.match(line):
            current.movements.append(_movement_from_match(match, current.account_id))

    return Trading212Statement(
        path=Path(path),
        generated_on=generated_on,
        period_start=period_start,
        period_end=period_end,
        accounts=accounts,
    )


def import_statement(path: str | Path, user_id: int | None = None) -> dict:
    """Import statement accounts, values and cash movements into ORION."""
    statement = parse_statement_pdf(path)
    uid = user_id if user_id is not None else get_default_user_id()
    if uid is None:
        raise RuntimeError("No ORION user exists yet. Launch ORION once first.")

    written = {"accounts": 0, "balances": 0, "transactions": 0}
    with session_scope() as session:
        source = session.scalars(
            select(DataSource).where(DataSource.user_id == uid, DataSource.key == "trading212")
        ).first()
        if source is None:
            source = DataSource(
                user_id=uid,
                key="trading212",
                name="Trading 212",
                domain=Domain.finance,
                status=SourceStatus.connected,
            )
            session.add(source)
            session.flush()
        source.status = SourceStatus.connected
        source.last_synced_at = datetime.now()
        _purge_placeholder_accounts(session, source.id)

        for item in statement.accounts:
            if item.label == "Invest Account" and item.value_minor == 0 and not item.movements:
                continue
            account = _account_for_statement_id(session, uid, source.id, item.account_id)
            if account is None:
                account = Account(
                    user_id=uid,
                    source_id=source.id,
                    name=_account_name(item.label),
                    kind=_account_kind(item.label),
                    currency=item.currency,
                    extra={},
                )
                session.add(account)
                session.flush()
                written["accounts"] += 1
            account.name = _account_name(item.label)
            account.kind = _account_kind(item.label)
            account.currency = item.currency
            account.extra = {
                **(account.extra or {}),
                "provider": "trading212_statement",
                "statement_account_id": item.account_id,
                "statement_label": item.label,
                "statement_path": str(statement.path),
                "statement_period_start": statement.period_start.isoformat()
                if statement.period_start
                else None,
                "statement_period_end": statement.period_end.isoformat()
                if statement.period_end
                else None,
                "statement_generated_on": statement.generated_on.isoformat(),
                "holdings_status": "positions_not_in_transactions_statement",
            }

            if _upsert_balance(session, account.id, statement.generated_on, item.value_minor, item.currency):
                written["balances"] += 1
            for movement in item.movements:
                if _transaction_exists(session, account.id, movement.external_id):
                    continue
                session.add(
                    Transaction(
                        account_id=account.id,
                        booked_at=movement.booked_at,
                        amount_minor=movement.amount_minor,
                        currency=movement.currency,
                        category=movement.category,
                        description=movement.description[:255],
                        extra={
                            "provider": "trading212_statement",
                            "external_id": movement.external_id,
                        },
                    )
                )
                written["transactions"] += 1
    return {
        **written,
        "generated_on": statement.generated_on.isoformat(),
        "period_start": statement.period_start.isoformat() if statement.period_start else None,
        "period_end": statement.period_end.isoformat() if statement.period_end else None,
    }


def _movement_from_match(match: re.Match[str], account_id: str) -> Trading212Movement:
    amount_minor = _money_minor(match.group("amount"))
    booked_at = datetime.strptime(match.group("when"), "%d/%m/%Y %H:%M:%S").date()
    note = match.group("note").strip()
    category = _category(note, amount_minor)
    external = _external_id(note) or _movement_fingerprint(account_id, booked_at, amount_minor, note)
    return Trading212Movement(
        amount_minor=amount_minor,
        currency="GBP",
        booked_at=booked_at,
        category=category,
        description=_sanitize_note(note),
        external_id=external,
    )


def _parse_period(text: str) -> tuple[date | None, date | None]:
    match = _PERIOD_RE.search(text)
    if not match:
        return None, None
    return (
        datetime.strptime(match.group(1), "%d.%m.%Y").date(),
        datetime.strptime(match.group(2), "%d.%m.%Y").date(),
    )


def _parse_generated_on(text: str) -> date | None:
    match = _GENERATED_RE.search(text)
    if not match:
        return None
    try:
        return datetime.strptime(match.group(1), "%d %B %Y").date()
    except ValueError:
        return None


def _money_minor(value: str) -> int:
    return int(round(float(value.replace(",", "")) * 100))


def _category(note: str, amount_minor: int) -> str:
    lower = note.lower()
    if "interest on cash" in lower:
        return "interest"
    if "payout" in lower or "sent to bank account" in lower:
        return "withdrawal"
    if amount_minor > 0:
        return "deposit"
    return "investment_cash"


def _sanitize_note(note: str) -> str:
    note = re.sub(r"Sent to Bank Account\s+\d{2}-\d{2}-\d{2}\s*/\s*\d+", "Sent to bank account", note)
    note = re.sub(r"Transaction ID:\s*[0-9a-f-]{20,}", "Transaction ID stored", note, flags=re.I)
    return note


def _external_id(note: str) -> str:
    match = _TRANSACTION_ID_RE.search(note)
    return match.group(1) if match else ""


def _movement_fingerprint(account_id: str, booked_at: date, amount_minor: int, note: str) -> str:
    return hashlib.sha256(f"{account_id}|{booked_at}|{amount_minor}|{note}".encode()).hexdigest()


def _account_for_statement_id(session, user_id: int, source_id: int, statement_id: str):
    rows = session.scalars(
        select(Account).where(Account.user_id == user_id, Account.source_id == source_id)
    ).all()
    for row in rows:
        if (row.extra or {}).get("statement_account_id") == statement_id:
            return row
    return None


def _purge_placeholder_accounts(session, source_id: int) -> None:
    rows = session.scalars(select(Account).where(Account.source_id == source_id)).all()
    for account in rows:
        extra = account.extra or {}
        if extra.get("provider") == "trading212_statement":
            continue
        if account.name != "Trading 212":
            continue
        for txn in session.scalars(select(Transaction).where(Transaction.account_id == account.id)).all():
            session.delete(txn)
        for balance in session.scalars(
            select(BalanceSnapshot).where(BalanceSnapshot.account_id == account.id)
        ).all():
            session.delete(balance)
        session.delete(account)


def _upsert_balance(
    session,
    account_id: int,
    snapshot_date: date,
    balance_minor: int,
    currency: str,
) -> bool:
    existing = session.scalars(
        select(BalanceSnapshot).where(
            BalanceSnapshot.account_id == account_id,
            BalanceSnapshot.snapshot_date == snapshot_date,
        )
    ).first()
    if existing is None:
        session.add(
            BalanceSnapshot(
                account_id=account_id,
                snapshot_date=snapshot_date,
                balance_minor=balance_minor,
                currency=currency,
            )
        )
        return True
    changed = existing.balance_minor != balance_minor or existing.currency != currency
    existing.balance_minor = balance_minor
    existing.currency = currency
    return changed


def _transaction_exists(session, account_id: int, external_id: str) -> bool:
    rows = session.scalars(select(Transaction).where(Transaction.account_id == account_id)).all()
    return any((row.extra or {}).get("external_id") == external_id for row in rows)


def _account_name(label: str) -> str:
    if label == "ISA Account":
        return "Trading 212 Stocks & Shares ISA"
    if label == "Cash ISA Account":
        return "Trading 212 Cash ISA"
    return f"Trading 212 {label}"


def _account_kind(label: str) -> str:
    if label == "Cash ISA Account":
        return "savings"
    return "investment"
