from __future__ import annotations

from app.integrations.trading212.activity_statement import parse_activity_statement_text


def test_parse_activity_statement_open_positions():
    text = """
Generated by Trading 212 UK Ltd. on 24 June 2026
Open positions
Ticker ISIN Currency Quantity Average price Current price Result Value Exchange rate Result (GBP) Value (GBP)
SSIT GB00BKPG0138 GBX 44.89218683 195.04507618 181.2 -621.54 8134.4643 100 -6.22 81.34
SXR8 IE00B5BMR087 EUR 0.10993794 640.08839896 703.98 7.02 77.3941 1.15984 5.58 66.73
Stocks ISA account - cash breakdown
"""

    statement = parse_activity_statement_text(text)

    assert statement.generated_on.isoformat() == "2026-06-24"
    assert len(statement.positions) == 2
    assert statement.positions[0].ticker == "SSIT"
    assert statement.positions[0].isin == "GB00BKPG0138"
    assert statement.positions[0].quantity == 44.89218683
    assert statement.positions[0].value_gbp == 81.34
    assert statement.positions[1].name == "iShares Core S&P 500 (Acc)"
