from __future__ import annotations

from app.integrations.trading212.statement import parse_statement_text


def test_parse_trading212_statement_text_extracts_isa_value_and_flows():
    statement = parse_statement_text(
        """
Generated by Trading 212 UK Ltd. on 25 June 2026 at 10:30 (UTC).
Document period 01.12.2025 - 24.06.2026
ISA Account
Account value: £274.35
Account ID: 35307388
AMOUNT CURRENCY TIME TRANSACTION TYPE NOTES
100 GBP 24/06/2026 06:38:24 TrueLayer Transaction ID: abcdef12-1234-1234-1234-abcdefabcdef
-99.98 GBP 20/05/2026 01:56:00 JP Morgan payout Sent to Bank Account 60-83-71 / 41491398
0.01 GBP 20/05/2026 01:08:12 Interest on cash Interest on cash
Cash ISA Account
Account value: £1.58
Account ID: 35307412
0.01 GBP 03/05/2026 01:33:10 Interest on cash Interest on cash
""",
        "statement.pdf",
    )

    assert statement.generated_on.isoformat() == "2026-06-25"
    assert statement.period_start.isoformat() == "2025-12-01"
    assert statement.period_end.isoformat() == "2026-06-24"
    isa = statement.accounts[0]
    assert isa.label == "ISA Account"
    assert isa.value_minor == 27435
    assert [m.category for m in isa.movements] == ["deposit", "withdrawal", "interest"]
    assert "41491398" not in isa.movements[1].description
